version: "3.9"

services:
  master:
    ports:
      - "8080:8080"
    image: spark:3.11
    environment:
      - SPARK_MODE=master
  worker:
    image: spark:3.11
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_CORES=2
    volumes:
      - spark-data:/workspace
  thrift:
    image: spark:3.11
    depends_on:
      - master
    environment:
      - SPARK_MODE=thrift
      - SPARK_MASTER_URL=spark://master:7077
    volumes:
      - spark-data:/workspace
  jupyerhub:
    image: jupyterhub3:spark311
    volumes:
      - spark-data:/workspace
    ports:
      - "8000:8000"
  debian:
    image: debian:latest
    entrypoint: "chmod 0777 -R /workspace"
    volumes:
      - spark-data:/workspace
  
volumes:
  spark-data: