name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME_SPARK: "parjanya/spark:331"
  IMAGE_NAME_JUPYTER: "parjanya/jupyterhub:spark331"

jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push Spark
        uses: docker/build-push-action@v3
        with:
          context: ./spark/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME_SPARK }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Scan Spark container image
      #   uses: anchore/scan-action@v3
      #   id: scan_spark
      #   with:
      #     image: ${{ env.IMAGE_NAME_SPARK }}
      #     fail-build: false
          #severity-cutoff: critical
          #acs-report-enable: true

      # - name: upload Anchore scan SARIF report
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}

      # - name: Inspect action SARIF report
      #   if: always()
      #   run: cat ${{ steps.scan.outputs.sarif }}

  jupterhub:
    needs: spark
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push Jupyterhub
        uses: docker/build-push-action@v3
        with:
          context: ./jupyterhub/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME_JUPYTER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Scan Jupyterhub container image
      #   uses: anchore/scan-action@v3
      #   id: scan_jupyterhub
      #   with:
      #     image: ${{ env.IMAGE_NAME_JUPYTER }}
          fail-build: false
          #severity-cutoff: critical
          #acs-report-enable: true

      # - name: upload Anchore scan SARIF report
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}

      # - name: Inspect action SARIF report
      #   if: always()
      #   run: cat ${{ steps.scan.outputs.sarif }}
