name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME_SPARK: "parjanya/spark331"
  IMAGE_NAME_JUPYTER: "parjanya/jupyterhub_spark331"

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          use_github_release_notes: true

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

  spark:
    needs: release-on-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push Spark
        uses: docker/build-push-action@v3
        with:
          context: ./spark/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME_SPARK }}:${{ needs.release.outputs.tag_name }},${{ env.IMAGE_NAME_SPARK }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  jupterhub:
    needs: [release-on-push, spark]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push Jupyterhub
        uses: docker/build-push-action@v3
        with:
          context: ./jupyterhub/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME_JUPYTER }}:${{ needs.release.outputs.tag_name }},${{ env.IMAGE_NAME_JUPYTER }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


