name: ci

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME_SPARK: "parjanya/spark:331"
  IMAGE_NAME_JUPYTER: "parjanya/jupyterhub:spark331"
jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: spark
          file: spark/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.IMAGE_NAME_SPARK }}

      - name: Scan local container image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ env.IMAGE_NAME_SPARK }}
          fail-build: false
          #severity-cutoff: critical
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Inspect action SARIF report
        if: always()
        run: cat ${{ steps.scan.outputs.sarif }}
